### ISSUE TITLE
Rendering bug causes match results to be indented too far

### ISSUE THREAD

**Issue by piafaustino** [thinkingmachines/linksight#104]
<img width="1242" alt="screen shot 2018-08-14 at 5 13 21 pm" src="https://user-images.githubusercontent.com/1260018/44083056-9336752e-9fe5-11e8-8619-bbb179d47b62.png">

**Comment by marksteve** [comment]
CSS Grid bug when there are lots of cells.  Can be fixed either by pagination or using [react-virtualized](https://bvaughn.github.io/react-virtualized/#/components/List). Either solution isn't doable by milestone "Release 0.2" :(
