### ISSUE TITLE
Non-results show up at exact matches

### ISSUE THREAD

**Issue by piafaustino** [thinkingmachines/linksight#106]
Try matching this test dataset.

When it is unable to find a PSGC match for the province of "Wakanda", LinkSight then proceeds to look for a match for the city of "Buenavista." However, instead of returning all the possible municipalities with the name "Buenavista" (there are at least two: one in Agusan del Norte, and another in Quezon Province), it returns as an exact match the one in Quezon Province. This is incorrect. 

[linksight-nonresult-testing.csv.zip](https://github.com/thinkingmachines/linksight/files/2286305/linksight-nonresult-testing.csv.zip)

Note the first two rows:
<img width="934" alt="screen shot 2018-08-14 at 5 37 39 pm" src="https://user-images.githubusercontent.com/1260018/44084250-c974b2f6-9fe8-11e8-9373-da7c102e2f2f.png">

**Comment by florobarotjr** [comment]
@marksteve, for now I marked a non-matched as `matched == False`. However, this results to the UI treating it as a multi match (with NAs, and mismatch as options).

Should we just convert the `matched` field to something else? To indicate a complete mismatch?

**Comment by marksteve** [comment]
@florobarotjr Do we handle the case where upper levels don't match but lower levels do?

**Comment by marksteve** [comment]
@florobarotjr Don't create a `MatchItem` for no matches na lang.

**Comment by piafaustino** [comment]
Suggestion from @marksteve:
Exact match = True
Multiple matches = False
No matches = Null
