### ISSUE TITLE
"Poblacion" barangays show up as "Acion" in the match results

### ISSUE THREAD

**Issue by piafaustino** [thinkingmachines/linksight#113]
<img width="473" alt="screen shot 2018-08-14 at 5 13 28 pm" src="https://user-images.githubusercontent.com/1260018/44083121-b59f8cf4-9fe5-11e8-8b39-c20764cd3019.png">

**Comment by piafaustino** [comment]
This has to do with how the reference file was cleaned. All instances of Pob. were stripped. Will fix this.

**Comment by piafaustino** [comment]
Oops I can't get this notebook to run locally for me. The ** must be a Python 3 thing.

**Comment by piafaustino** [comment]
The issue is in cell 40:

```
barangays['location'] = (barangays['location']
                         .str.upper()
                         .str.replace('\(?POB.\)?', '')
                         .str.strip())
```

**Comment by florobarotjr** [comment]
Fixed regex in https://github.com/thinkingmachines/data/pull/4
