### ISSUE TITLE
"0.00" comes up as suggestion, cannot be unclicked when clicked

### ISSUE THREAD

**Issue by daniellegayares** [thinkingmachines/linksight#124]
![image](https://user-images.githubusercontent.com/33336908/44132597-4d3e9ea4-a08d-11e8-89e9-e7e17b741482.png)

Additionally, these values are expected to be matched as municipality, province and region are spelled exactly the same as with the PSGC reference.

**Comment by syk0saje** [comment]
@daniellegayares What dataset did you use and what columns did you select? Cannot reproduce with FamilyDOC dataset and correct columns.

**Comment by syk0saje** [comment]
as per @daniellegayares:
> tried the datasets i have. it doesn't happen anymore. probably corrected in the changes
