### ISSUE TITLE
As a user, I want to know the number of "Multiple Matches" I need to check and how many I've already done

### ISSUE THREAD

**Issue by daniellegayares** [thinkingmachines/linksight#125]
![image](https://user-images.githubusercontent.com/33336908/44132793-6cb03a8a-a08e-11e8-833d-37cefd9298c2.png)

Current status: Changing numbers in Multiple Matches and Checked Matches. A bit confusing, I initially thought there were three results (Identified Locations, Multiple Matches, and Checked Matches).

Suggestions:

1. Separate the placing of Checked Matches and add the instructions near this.

2. Convert this to a numerical goal ratio (Checked/Multiple Matches). Fixed number on multiple matches and change checked matches as user selects. Example: starts at 0/258. Then as person selects, it moves to 1/258, 2/258 until 258/258. 

3. Visual progress bar to motivate the user to decide on the goal number.

**Comment by piafaustino** [comment]
@binkymilk Can you take on designing how this should look and later coding it up too? For Monday release

**Comment by binkymilk** [comment]
Tried out a new way of representing both the number of multiple matches and the number of matches already checked

![linksight-v3-02](https://user-images.githubusercontent.com/26348221/44257244-02982e80-a23e-11e8-9ef7-1ef134d91b1f.png)

**Comment by piafaustino** [comment]
Closing for now because we're doing an overhaul of the check matches page #185 

Let's revisit this later
