### ISSUE TITLE
Common Municipality Names get tagged as "No Match"

### ISSUE THREAD

**Issue by daniellegayares** [thinkingmachines/linksight#128]
![image](https://user-images.githubusercontent.com/33336908/44135639-8923861e-a09c-11e8-9b11-89c1233a8814.png)

The ones tagged as No Match doesn't show suggestions. Just the 4 entries under "Checked". 

Original Dataset: https://docs.google.com/spreadsheets/d/1L_iHMGyhQuxVcDOOIKpr4YJF3b56oR53raL1wKKWbSY/edit?usp=drive_web

Result of matching: https://docs.google.com/spreadsheets/d/1z4zHbWDiLDP9peL0EdXljStINlf7JEzU27wyft2mkwg/edit#gid=2053913447

**Comment by florobarotjr** [comment]
Already checked a select number of 'no matches' separately and they are being matched properly. Still investigating why it's not marking them as such when processed as part of this dataset.

**Comment by piafaustino** [comment]
Experienced similar problem with linksight-testing.csv. 137 no matches that should have at least had candidates.

**Comment by piafaustino** [comment]
@florobarotjr Please also add tag "For QA" for issues reassigned to the reporter for checking. thanks!

**Comment by piafaustino** [comment]
Processed this dataset again using LinkSight. Only 2 incorrect entries out of 1636!  It just couldn't find Bislig and Maguing:

<img width="689" alt="screen shot 2018-08-22 at 3 46 11 pm" src="https://user-images.githubusercontent.com/1260018/44450053-88dbb880-a622-11e8-819a-393a8509192e.png">

Will close for now and file Bislig and Maguing in Linksight 0.3
