### ISSUE TITLE
Remove "Checked Matches" from the match results. Retain "Multiple Matches", but the number should reflect the source rows for which there are multiple matches

### ISSUE THREAD

**Issue by piafaustino** [thinkingmachines/linksight#129]
Quick fix before we implement #125 to help the user track checking progress more effectively

![image](https://user-images.githubusercontent.com/1260018/44138315-1272c2dc-a0a6-11e8-871b-1440f2d46cd6.png)

**Comment by syk0saje** [comment]
work ongoing in https://github.com/thinkingmachines/linksight/tree/remove-checked-matches

**Comment by syk0saje** [comment]
@piafaustino please test and close if fixed

**Comment by piafaustino** [comment]
Looks good
