### ISSUE TITLE
Shariff Kabunsuan (2006-2008) is not in the PSGC but is a province in other datasets 

### ISSUE THREAD

**Issue by daniellegayares** [thinkingmachines/linksight#133]
Shariff Kabunsuan is a province in the MuniCity and Province PhilGIS basemaps (2011). It is a short-lived province in ARMM that was recognized in 2006 and disestablished in 2008. Today, the land is under the province of Maguindanao.

Currently, LinkSight tags it as "No Match". We have to form an accommodation in case people upload datasets with Shariff Kabunsuan.

**Comment by florobarotjr** [comment]
Since all of the municipalities are in Maguindanao, we can just add Shariff Kabunsuan as an alternate row for Maguindanao. Thoughts, @marksteve @piafaustino?

**Comment by piafaustino** [comment]
@florobarotjr Do you mean we will add additional/alternate rows to the reference file with Shariff Kabunsuan as the province? If I understand correctly, won't this return the correct PSG code but an outdated Matched Province column?

**Comment by syk0saje** [comment]
Related to #149
