### ISSUE TITLE
Accuracy Issues for 0.2

### ISSUE THREAD

**Issue by daniellegayares** [thinkingmachines/linksight#136]
**[Matched Dataset -LGU Competitiveness](https://docs.google.com/spreadsheets/d/1aXLZc_j8WclCVQ990et5qzGhUl_3ECnK1Srkmfgtl6g/edit#gid=1930936160)**

- [x] North Cotabato municipalities become exact matches for South Cotabato as province then null municipality

![image](https://user-images.githubusercontent.com/33336908/44198854-0ca22a80-a175-11e8-8422-c87cf05a366b.png)

- [x] Municipalities with "Leyte" as province are matched to "Southern Leyte" as province then null municipality

![image](https://user-images.githubusercontent.com/33336908/44198874-1cba0a00-a175-11e8-882d-56acca199f35.png)

- [x] Municipality of "President Garcia"(dataset) in Bohol did not get matched to "PRES. CARLOS P. GARCIA" (PSGC) - null matched municipality, matched province

**[Matched Dataset - Fiscal Data](https://docs.google.com/spreadsheets/d/1WdmFdejbDjmkjaMmT062GxClk0W_AL_FFwS4P6qRjlc/edit#gid=1600978060)** 

- [x] Inaccurate matching: Mandaluyong City, matched with Tandag, Surigao del Sur
- [x] Inaccurate matching: Naga City (Cebu) and Talisay City (Cebu)

![image](https://user-images.githubusercontent.com/33336908/44198467-14150400-a174-11e8-9461-f791f56819d8.png)

- No municipality matched for these locations with "city" (UPDATE 2018/08/20: Filed as separate issue #141 )

![image](https://user-images.githubusercontent.com/33336908/44198743-c51b9e80-a174-11e8-835f-eb9e42f92f52.png)

-----

**[Matched Dataset: Barangay Level Poverty Indicators](https://docs.google.com/spreadsheets/d/1jMwZtIgX_Cm9FxPou2j6dmwq_OT3Cx3DiJVcGzVVvbg/edit#gid=1804281386)**
- [x] Barangays named Poblacion N, in which the N is a number with 2 digits, get incorrectly matched as exact:
<img width="290" alt="screen shot 2018-08-16 at 4 28 53 pm" src="https://user-images.githubusercontent.com/1260018/44197590-a5cf4200-a171-11e8-8b52-b54ca7ef228f.png">

- In cases where the input data contains a barangay that is placed in an incorrect municipality, LinkSight identifies these as "Exact Match" when they should be at the very least a "No Match". Example below. Our input dataset mislabelled various barangays as being in "Itbayat" when they are really in "Ivana." These were matched with Itbayat province and considered an "Exact Match." (UPDATE 2018/08/20: Filed as separate issue #141 )

<img width="686" alt="screen shot 2018-08-16 at 5 19 29 pm" src="https://user-images.githubusercontent.com/1260018/44200631-a4a21300-a179-11e8-8a58-cedd51be04fe.png">

- [x] 75%  of the rows in the matched dataset are missing values for the fields "Population" and "Administrative Level" even though the rows were matched with a PSGC code. 

LinkSight incorrectly classifies Plaridel (Santa Elena) as an exact match with Santa Elena (Pob.). This is because of the nature of the current substring matching loop which stops when the first instance of a substring match is found. Solutions:

- [x] Update the algorithm to include all substring matches as near matches.

- [x] Classify as "Exact Matches" only those that return results the exact string matching section of our algorithm. For substring or fuzzy matches, these should all be considered near matches, even if only one possible match exists. It's better to have the user manually review and correct all matches that are not certain.

---

**[DSWD data tested by Reg Onglao](https://docs.google.com/spreadsheets/d/1jMwZtIgX_Cm9FxPou2j6dmwq_OT3Cx3DiJVcGzVVvbg/edit#gid=1352789785&range=A2)** 

- When the input data has a city/municipality misplaced in the Barangay column, LinkSight can't find the correct result.  Feedback from Reg Onglao: "I used one of my old DSWD files, and found multiple cases wherein encoders put a "city/municipality" in the "barangay" column instead (I imagine this'd be a usual error for govt agencies). I'm wondering if your algo can check these human error cases if there's a higher-accuracy match by moving one admin level up (vs a low-accuracy match within same admin level)? Here's an example below. This should have been matched to Tabaco City, Albay but had bad results since was forced to be a Barangay:" (UPDATE: Moving to Release 0.3. Filed as separate issue #141 )
![image](https://user-images.githubusercontent.com/1260018/44205215-3284fa80-a188-11e8-9a34-53068fa7266d.png)

- [x] "Bantayan Island" should have been matched to Bantayan, not Daanbantayan. The complex part here is that the keyphrase is an island with 3 municipalities in it, so your algorithm missed this geographic link.

![image](https://user-images.githubusercontent.com/1260018/44205318-87c10c00-a188-11e8-9cbe-72b01cd39ff6.png)

- [x] "Sitio Bautista" should return multiple matches for all possible barangays with the name Bautista in it

![image](https://user-images.githubusercontent.com/1260018/44205335-96a7be80-a188-11e8-859d-13a32bc7861f.png)

- [x] Instead of an "exact" match, this example should have given multiple choices -- specifically, mapped to 2 possible results (Concepcion, Iloilo and Batad, Iloilo) instead of only providing 1 exact match. 

![image](https://user-images.githubusercontent.com/1260018/44205357-a9ba8e80-a188-11e8-98aa-c8cf4785fd77.png)

- [x] For 7 rows where the source province was "Samar", LinkSight returned "Eastern Samar" as an exact match at the province level and did not find any matches for source municipalities and barangays provided. This is both incorrect and incomplete. LinkSight should have matched Samar with "Western Samar." If so, it would have found most of the source municipalities listed:

- Almagro, Samar
- Calbiga, Samar
- Daran, Samar
- Matuguihap, Samar
- Santa Margarita, Samar
- Sta. Margarita, Samar
- Villareal, Samar

**[Matched Dataset - Education](https://docs.google.com/spreadsheets/d/1vSQ73LBtb1rDFJfz2msbtXG_gH-w4oCqyD0mbMa8t1A/edit#gid=510857299)**

![image](https://user-images.githubusercontent.com/33336908/44455095-ca269500-a62f-11e8-9883-65e02a317dcd.png)

3 entries showed up blank on Matched Municipality on export. But upon processing, 0 "no matches" and these did not appear when choosing recommendations.

- [x] Science City of Muñoz not matched to Muñoz, City of Bñan not matched to Biñan. Problem on recognizing ñ?
- [x] Ozamis City not matched to Ozamiz 

**[Matched Dataset - Listahanan](https://docs.google.com/spreadsheets/d/1GFVgYSwJUr73ovjrZWpWbU32JyhHiDuAX8dIl7_2j1s/edit#gid=403001102)**

- [x] Barangays in "Caloocan" do not get exact matches with "Kalookan". Correct one appears among the recommendations.  Taxing if selection has to be done more than 20 times.  

In relation to the above, the following match should also be considered "exact" because it's an exact string match across all available columns:

<img width="836" alt="screen shot 2018-08-23 at 5 45 48 pm" src="https://user-images.githubusercontent.com/1260018/44518383-aed58b80-a6fc-11e8-8459-e09c71b8deb6.png">

- [x] Reference locations with an enye character in the name are not scored as highly. Enyes in the reference files needs to be replaced with a regular N.

**Comment by florobarotjr** [comment]
**Re: `Itbayat`**
This happens because we check for matches from the higher interlevel first. So we rely on the higher interlevel being correct. If we found a match at the MuniCity level but found none, we said that we should return the deepest we can find. In this case, it's MuniCity, do we want to change that such that if we don't find a match at the lower interlevel, even if one is provided, the whole thing will be marked as 'No match'?

This applies to the last item as well.

**Re: locations with city**
A number of these rows were placed on incorrect provinces. Surigao, Bislig, and Tandag are under Surigao del Sur, not Agusan del Sur so they are not being matched. Same case for Bacolod City.
Looks like we really need one-go type of matching that will consider the whole thing rather than per-interlevel if we want to do this level of correction.

**Comment by piafaustino** [comment]
Filing a new issue for handling and describing edge cases in which the source data provides a lower-level administrative unit that is not located within the higher level administrative unit provided.

**Comment by piafaustino** [comment]
@florobarotjr This issue ("Sitio Bautista" should have been matched to Escalante City, Negros Occidental) seems like it was also being caused the by substring matches being considered "exact." Is this correct?

**Comment by florobarotjr** [comment]
@piafaustino, the issue with the missing `Population` and `Administrative Level` values was due to incorrect codes set in the `population.csv` file. Pandas treats the PSGC as integer so it removes the zero-pad at the start. 

I've fixed the file and uploaded it in GCS. I'll update the prod instance to use the file.

**Comment by florobarotjr** [comment]
@piafaustino, yup but I noticed that there's no **Sitio Bautista** under **Escalante City**. I only have the following barangays under it: https://psa.gov.ph/classification/psgc/?q=psgc/barangays/064509000

**Comment by florobarotjr** [comment]
@piafaustino, if only `Sitio Bautista` was provided and no other higher interlevel values, we will still return multiple matches because we don't have a way to limit the reference dataset.

**Comment by piafaustino** [comment]
@florobarotjr Ah yes, the Sitio Bautista returns multiple values.

**Comment by piafaustino** [comment]
Remaining issues should be addressed by latest matcher. Closing for now
