### ISSUE TITLE
Suggestion for improving speed: Use filtered/smaller reference files if Municipality/City or Province are selected by user as lowest granularity in source dataset

### ISSUE THREAD

**Issue by piafaustino** [thinkingmachines/linksight#146]
There are 43k barangays, but only 1600+ cities and municipalities. If the smallest granularity selected by the user in their source file is "municity" and not "barangay", then we can use a much smaller reference file of 1600+ rows only instead of 43k. Hopefully, this should improve performance for those who don't need to match at the barangay level.

**Comment by marksteve** [comment]
We sort of do this now in the algorithm. Columns are only compared to their respective subsets of the reference file.
