### ISSUE TITLE
Add tests for requirements

### ISSUE THREAD

**Issue by syk0saje** [thinkingmachines/linksight#147]
The output dataset will contain:

- [x] If it's an exact string match, do not include near matches
- [x] The client should not be required to upload all fields so the matcher should be able to provide the most accurate results based on which fields are available
- [x] If there are no exact matches, return the possible matches. The possible matches should be sorted with the nearest match at the top
- [x] If a higher interlevel has no match or was not provided, the matcher should be able to infer it from the lower interlevel match. Example: If only Dasmarinas (city) was provided, the resulting dataset should include Cavite (province)
- [x] convert edge_cases Google Sheet into tests: https://docs.google.com/spreadsheets/d/1yni0PH2b65VPbPoJpAJOT6j4QF0uRA8MiMS6JefGi0c/edit#gid=0

**Comment by syk0saje** [comment]
Removed the following item as it not feasible to test right now:
> The correct match should be in the top 5 of the choices 95% of the time (and top 1 60% of the time)

**Comment by syk0saje** [comment]
Will hold off on closing until I've updated this to the improved matcher usage from @florobarotjr

**Comment by florobarotjr** [comment]
@daniellegayares, I tested this and tests are working. I added a comment in https://github.com/thinkingmachines/linksight/pull/199#issuecomment-421241200 but that can be a separate issue to ease the tests of alternative algo approaches. This should be good to close

cc @syk0saje
