### ISSUE TITLE
When I upload a dataset, I want to be able to correct the datatype auto-detected by LinkSight for each column

### ISSUE THREAD

**Issue by piafaustino** [thinkingmachines/linksight#153]
I uploaded a [test dataset](https://docs.google.com/spreadsheets/d/1jMwZtIgX_Cm9FxPou2j6dmwq_OT3Cx3DiJVcGzVVvbg/edit#gid=1352789785&range=A21) that contained an answer key of expected PSGC values. LinkSight converted this column to numbers, but I need for it to remain as a text column because of the leading zeroes. See screengrab below of the expected_psgc column in which the leading zeroes got chopped off:

<img width="423" alt="screen shot 2018-08-21 at 5 48 54 pm" src="https://user-images.githubusercontent.com/1260018/44394797-a9e0d280-a56a-11e8-9949-cc2d57ad174e.png">

We need to have a feature that will allow the user to manually change any auto-detected datatypes per column.

**Comment by marksteve** [comment]
@piafaustino Hmm. Let's add this as we add export filetypes? Right now we only export to CSVs and everything is a string in CSVs (parsers just try to detect data types and coerce to native types). So we can just make everything strings when we load datasets and it should be all good.

**Comment by piafaustino** [comment]
Putting in backlog for now. This should be addressed by #155
