### ISSUE TITLE
Include match confidence level in exported results

### ISSUE THREAD

**Issue by piafaustino** [thinkingmachines/linksight#154]
While we're still improving LinkSight's accuracy, let's encourage users to double-check match results by providing a confidence level for each in the exported dataset. There can be three categories, consistent with what we use in our "Check Matches" view:

1. **Exact Match** = 100% string match across all interlevels provided
2. **Near or Partial Match** = Anything less than above. This encompasses naming variations, abbreviations, and missing values in the source data.  This is currently called "Multiple Matches" in the UI but Near or Partial Match might be a more appropriate term, since you can have only 1 potential match but it's still just partial or near.
3. **No Match** = Nothing at all found

**Comment by marksteve** [comment]
@piafaustino Think of issues as a discussion rather than a checklist. You can add checklists in an issue for a reason!

**Comment by piafaustino** [comment]
Oks got it @marksteve, will close this and just update 141!
