### ISSUE TITLE
Set all column datatypes to string in export dataframe

### ISSUE THREAD

**Issue by marksteve** [thinkingmachines/linksight#155]
Right now column datatypes are auto-detected and truncates some number-like columns (such as the PSGC). Set all column datatypes to string to keep source to export lossless. This only applies to CSV exports w/c is the only export type right now (See #153)

**Comment by piafaustino** [comment]
@marksteve new bug: Blank or unmatched PSG codes now appear in the exported dataset as the string "nan." They should instead be an empty string or null.

**Comment by piafaustino** [comment]
[reg-onglao-test-matched_cKzIPz6.csv.zip](https://github.com/thinkingmachines/linksight/files/2359282/reg-onglao-test-matched_cKzIPz6.csv.zip)

**Comment by marksteve** [comment]
Related: https://sentry.thinkingmachin.es/thinking-machines/linksight/issues/625/?referrer=slack

**Comment by piafaustino** [comment]
Closing because "nan" no longer appears as a value in the PSGC column
