### ISSUE TITLE
Revamp matching algorithm

### ISSUE THREAD

**Issue by florobarotjr** [thinkingmachines/linksight#16]
Suggestions:
- split the PSGC code into their own parts
- for matching, use [`recordlinkage`](http://recordlinkage.readthedocs.io/en/latest/) first, then use [`fuzzywuzzy`](https://github.com/seatgeek/fuzzywuzzy) for parts where we don't see an easy match
- make the interlevels generic for usability
- also look into [`dedupe`](https://github.com/dedupeio/dedupe)

User acceptance test
- [x] Algorithm can process 100 rows in under 15 seconds
- [x] Algorithm can handle datasets that are missing barangay, municipality/city, or province (any combination of these three levels)

**Comment by marksteve** [comment]
I think @liangi meant exact matches first then fuzzywuzzy?
