### ISSUE TITLE
Improve "processing" icon

### ISSUE THREAD

**Issue by daniellegayares** [thinkingmachines/linksight#162]
![image](https://user-images.githubusercontent.com/33336908/44507013-8d17dc80-a6db-11e8-96b3-a4d23bcce931.png)

Actual user feedback: "Is this working or is it stuck?"
Suggestion: Progress Bar

**Comment by piafaustino** [comment]
@marksteve Did you mention that it might be possible to have a counter that estimates how much of the dataset is done? 

For:

200/1675 locations matched

And this can keep updating as the algo processes

**Comment by piafaustino** [comment]
Closing for now. To be addressed by #185
