### ISSUE TITLE
Change user account access to one step Google Sign-in

### ISSUE THREAD

**Issue by piafaustino** [thinkingmachines/linksight#167]
Because LinkSight is still in alpha phase and needs active feedback, we need to limit access:

**Log In or Sign Up**
- [x] When first visiting LinkSight, users will be prompted to either Log In by entering their e-mail address or Sign Up.

  **Log In**
  - [x] If a user provides an already authorized e-mail address, he/she can proceed to use LinkSight.
  - [x] If a user provides an unauthorized e-mail address, he/she will see a prompt that says "Oops! You haven't signed up yet!"

  **Sign Up**
  - [x] If a user clicks "Request access", he or she will go to a Google Form where he/she can answer a few questions and provide his/her email address. (@daniellegayares could you do the sign-up form?)
  - [x] After entering the email address, a message will appear saying "Thanks for your interest in using this tool. You'll be notified as soon as access is approved."

**Approving Users**
- [x] @daniellegayares can approve e-mail addresses via a separate interface (@marksteve can this just be a simple google sheet with one column for email addresses and another for "approved" that is simply a checkbox? Or are there out of the box admin panels for approving email access?)
- [x] Approved addresses will receive an automatic notification of their approval. (@daniellegayares and by automatic I just mean, you'll send them one right away haha)
- [x] @daniellegayares can customize the content of the email notification for approved users.
- [x] The 50+ users who requested access before will be added to the spreadsheet of authorized users.

**Comment by piafaustino** [comment]
I got feedback from mgmt team confirming that current sign-up process is too tedious.  Let's please implement instead the original treatment described above: 

Changes:
- [ ] Use one-step Google Sign-In instead of asking people to create their own user accounts with new passwords. It lends credibility when we use a standard sign-in like Google or Facebook rather what appears to be our own system. It's a lot to also ask people to remember yet another password for a tool that is still in testing phase.
- [ ] Create a separate sign-up sheet as a Google Form where people will also respond to the survey. @daniellegayares can manually add these emails later to the admin panel of approved email addresses.

**Comment by piafaustino** [comment]
Complexity: 1/4 of a day

**Comment by piafaustino** [comment]
See new wireframes for simplified log-in: 
<img width="636" alt="screen shot 2018-09-17 at 1 29 42 pm" src="https://user-images.githubusercontent.com/1260018/45607267-d6124500-ba7d-11e8-8bc8-f19843aa0019.png">

If user's email is not authorized:

<img width="803" alt="screen shot 2018-09-17 at 1 29 47 pm" src="https://user-images.githubusercontent.com/1260018/45607260-cc88dd00-ba7d-11e8-8f7e-dec038a8c3ab.png">

@daniellegayares please provide @marksteve with link to Google Form

**Comment by piafaustino** [comment]
Reopening this issue until it's confirmed working on deployed front-end.

**Comment by marksteve** [comment]
@pepe @flo

Proposed execution:

1. Start from https://github.com/thinkingmachines/linksight/pull/225
2. Update SOCIAL_AUTH_PIPELINE, replace social_core.pipeline.social_auth.auth_allowed with our own auth check that downloads the sheet from Drive and reads the email as a whitelist. You can use the compute engine service account for auth.
3. Update UI to catch the auth error and show Bianca's error message

**Comment by piafaustino** [comment]
This works! Closing
