### ISSUE TITLE
All exported datasets have a superfluous column called Unnamed 0

### ISSUE THREAD

**Issue by piafaustino** [thinkingmachines/linksight#174]
It looks like some kind of index being added as an extra column:

<img width="968" alt="screen shot 2018-08-30 at 2 02 37 pm" src="https://user-images.githubusercontent.com/1260018/44832454-7afae880-ac5d-11e8-9ca9-82fdf7cafd6f.png">

**Comment by syk0saje** [comment]
@piafaustino i can't reproduce this. could you post more detailed information on how?

**Comment by piafaustino** [comment]
Closing because this has been referenced as a checkbox in #185
