### ISSUE TITLE
Expose LinkSight API for developer consumption

### ISSUE THREAD

**Issue by clar-reese** [thinkingmachines/linksight#184]
Internally at least, we should probably have a way to geocode that makes the geocoding automatic (part of the pipeline) as new data comes in; we shouldn't need to have to go through the website every time there's new data.

We're probably going to need this functionality for client, and will likely need it for future geospatial projects as well.

**Comment by marksteve** [comment]
This can be implemented through the API w/c actually exists now.

**Comment by piafaustino** [comment]
What done looks like:
- [ ] Add a "I feel lucky" toggle to the match end-point to get the single best match for each row (lucky=True)
- [ ] Add token authentication 
- [ ] Add and deploy API documentation
- [ ] Update readme to include example usage
