### ISSUE TITLE
Add confirm choice in Check step

### ISSUE THREAD

**Issue by marksteve** [thinkingmachines/linksight#198]
The count of multiple matches for review doesn't change when a selection was made (w/c is the default state, top choice). But it goes down when you select "No match" w/c is feels weird.  We can remove "No match" from the choices and move it to a button set:

🔵 Barangay, City/Municipality, Province
⚪️ Barangay, City/Municipality, Province
⚪️ Barangay, City/Municipality, Province

<kbd>Select candidate</kbd> <kbd>No correct match / Unsure</kbd>

**Comment by piafaustino** [comment]
Irrelevant with the new panel UI
