### ISSUE TITLE
Allow user to try Linksight using a provided demo CSV file

### ISSUE THREAD

**Issue by piafaustino** [thinkingmachines/linksight#219]
This can make testing the product somewhat easier/faster if we have a sample dataset that users can just load automatically. In the "upload page" we can give people the option to just load a sample dataset that has multiple examples of messy names.

**Comment by daniellegayares** [comment]
Quick fix in #185: "Don't have a dataset? You can also use sample datasets [here](https://drive.google.com/drive/u/0/folders/1Yo1Y68fLnOcj_x-AEQh-V5S7_H08s_IV)."
