### ISSUE TITLE
Fix Tagaytay being found as a Barangay and not a Municipality/City

### ISSUE THREAD

**Issue by piafaustino** [thinkingmachines/linksight#222]

**Comment by piafaustino** [comment]
Hopefully addressed by https://github.com/thinkingmachines/linksight/commit/4a4a9aee98318c59d82f7684371cf0a9f19f87eb: Changed the scoring mechanism to strengthen score of search terms, candidates with matching admin levels. It was a pure weight before, but now it has a multiplier effect.

**Comment by daniellegayares** [comment]
Still picking up barangay even if only municipality and province are specified


![image](https://user-images.githubusercontent.com/33336908/45804868-e29dd400-bcef-11e8-9821-2ee26fd165e9.png)

**Comment by piafaustino** [comment]
Pushed another fix here. It was an issue with how the search terms are cleaned. @daniellegayares

**Comment by piafaustino** [comment]
Confirmed fixed
