### ISSUE TITLE
Accuracy Issues 

### ISSUE THREAD

**Issue by daniellegayares** [thinkingmachines/linksight#223]
09/20/2018 

- [ ] Empty candidate 

![image](https://user-images.githubusercontent.com/33336908/45801887-d7df4100-bce7-11e8-866c-3307d88229f5.png)

![image](https://user-images.githubusercontent.com/33336908/45862545-c6a83a00-bda4-11e8-9158-f2b2d99cc629.png)

- [ ] Add region as admin level to specify to either consider in the matcher or as a visual placeholder for users to not wonder why it's not asked

- [ ] Inconsistent order of admin levels on NCR items

- [ ] Inconsistency in Region name of NCR Region on 1 is NCR and Metro Manila on 2

- [x]  Region is not specified in the original dataset, but shows up in the candidate matches

![image](https://user-images.githubusercontent.com/33336908/45803007-fabf2480-bcea-11e8-9aa1-dbc08e9ce7bb.png)

Correct answers not among the candidates
- [x] Malabon

![image](https://user-images.githubusercontent.com/33336908/45804458-bfbef000-bcee-11e8-90b7-6e225f995c14.png)

- [x] City of Tabuk
![image](https://user-images.githubusercontent.com/33336908/45804688-5d1a2400-bcef-11e8-912a-d9a271c19668.png)

- [x] Laoag

![image](https://user-images.githubusercontent.com/33336908/45804719-702cf400-bcef-11e8-8119-4fbd2b5e2a93.png)

- [x] Vigan

- [x] Malolos

- [x] Tarlac

![image](https://user-images.githubusercontent.com/33336908/45805139-9010e780-bcf0-11e8-82a8-113193098452.png)

- [x] "City of ABCDE" should be exact match to "ABC City"

- [x] Olongapo should have been first candidate

![image](https://user-images.githubusercontent.com/33336908/45805182-b171d380-bcf0-11e8-9903-58c7c96418c0.png)

- [x] Polilio, Quezon

- [x] Cordoba/Cordova

**Comment by piafaustino** [comment]
A lot of these might have been fixed with latest commit! 7c6871a23968cba4e03d21531d9f0445a1fd12f8 We weren't cleaning extra terms from the search strings properly.

**Comment by piafaustino** [comment]
Solved all these issues! The following remaining issues are will be covered by fixing the reference file #218:
- Empty candidate
- Inconsistent order of admin levels on NCR items 
- Inconsistency in Region name of NCR Region on 1 is NCR and Metro Manila on 2
