### ISSUE TITLE
Change sign-up form URL to Google Form

### ISSUE THREAD

**Issue by piafaustino** [thinkingmachines/linksight#239]
https://docs.google.com/forms/d/e/1FAIpQLScQPG4sol4rz8T5pgGe0LqZTllUNWkVzyipF3JANDWvOuc_AA/viewform

**Comment by syk0saje** [comment]
https://github.com/thinkingmachines/linksight/pull/238/commits/e2d855db7ad4a361a7955e02ea1c400233f7161c

**Comment by syk0saje** [comment]
https://github.com/thinkingmachines/linksight/pull/238
