### ISSUE TITLE
Fix reference file inaccuracies

### ISSUE THREAD

**Issue by syk0saje** [thinkingmachines/linksight#279]
Reported bugs in reference file:
- [x] There are cases of the same set of aliases referring to different PSG codes. For example, "dumalneg, dumalneg, ilocos norte" refers to PSGC codes 012810001 and 012810003.
- [x] Add as aliases location names that replace Z with S. Example: Legazpi and Legaspi

**Comment by piafaustino** [comment]
This is done! Just need to double-check in which directory to store it? [clean-psgc.csv.gz](https://github.com/thinkingmachines/linksight/files/2517759/clean-psgc.csv.gz)
