### ISSUE TITLE
Turn school coordinates into a test dataset by adding psgc code via qgis

### ISSUE THREAD

**Issue by syk0saje** [thinkingmachines/linksight#323]
23k rows

**Comment by binkymilk** [comment]
Used another dataset (of 7K+ rows) because the original dataset with 23K rows did not have longitude and latitude columns. 

The schools dataset with the correct location fields and PSGC can be found here: https://drive.google.com/open?id=1TJnaDSlVFAMjUPY2TYisJJwFqzLYBak-
