### ISSUE TITLE
LinkSight hangs on "Identifying Locations"

### ISSUE THREAD

**Issue by piafaustino** [thinkingmachines/linksight#46]
1) Select a file to upload
2) Select which columns correspond to barangay, city, province etc
3) Identifying locations takes forever

![linksight_video](https://user-images.githubusercontent.com/1260018/43395960-8eff390a-9432-11e8-80fd-bd3c02284820.gif)

**Comment by marksteve** [comment]
@piafaustino Error has been fixed! Close if it works for you.

**Comment by piafaustino** [comment]
This works! But until now I've never been able to successfully export a CSV. I'll file it separately
