### ISSUE TITLE
'DataFrame' object has no attribute 'original'

### ISSUE THREAD

**Issue by syk0saje** [thinkingmachines/linksight#74]
Introduced by line 64 on https://github.com/thinkingmachines/linksight/commit/e3ba20fc

**Comment by marksteve** [comment]
`original` column is introduced here: https://github.com/thinkingmachines/data/commit/8c477301ffd09b0986e63e2cddf9b344cd1f46af

So you need to update your psgc dataset

**Comment by syk0saje** [comment]
Fix noted. File in bucket has also been updated.
