### ISSUE TITLE
I get the correct match in the top 5 of choices 95% of the time for the following combinations of barangay, city/municipality, province, and region

### ISSUE THREAD

**Issue by piafaustino** [thinkingmachines/linksight#93]
- [ ] barangay, city/municipality, province, and region
- [ ] barangay and city/municipality, and region only
- [ ] city/municipality and province, and region only
- [ ] barangay, province, and region only
- [ ] city/municipality and region only
- [ ] province and region only
- [ ] barangay and region only
- [ ] region only

**Comment by syk0saje** [comment]
Obsoleted by #234
