### ISSUE TITLE
I want to see clearer error messages if data did not fit the requirements for processing

### ISSUE THREAD

**Issue by piafaustino** [thinkingmachines/linksight#99]

**Comment by daniellegayares** [comment]
![image](https://user-images.githubusercontent.com/33336908/44448301-74e18800-a61d-11e8-89aa-6bdf4c335d0f.png)

Dataset uploaded has 30k rows.

**Comment by piafaustino** [comment]
@daniellegayares @syk0saje is this finished?

**Comment by marksteve** [comment]
@piafaustino this has been fixed

**Comment by syk0saje** [comment]
For reference: https://github.com/thinkingmachines/linksight/pull/216

**Comment by marksteve** [comment]
@piafaustino max row count error is back! can we close this?
